services:
  backend:
    build:
      context: carGPT/backend
    ports:
      - "8000:8000"
    env_file:
      - carGPT/backend/.env

  frontend:
    build:
      context: carGPT/frontend
    ports:
      - "8501:8501"

  db:
    build:
      context: docker/database
      dockerfile: Dockerfile
    image: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: adsuser
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: