# Logging Configuration for CarGPT Backend
# This YAML file configures the logging system for the backend application.
# You can modify this file to customize logging behavior.

version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  simple:
    format: "%(levelname)s - %(name)s - %(message)s"
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "file": "%(filename)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  console_colored:
    format: "%(asctime)s - %(name)-20s - %(levelname)-8s - %(message)s"
    datefmt: "%H:%M:%S"

handlers:
  # Console output
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console_colored
    stream: ext://sys.stdout
  
  # Main application log file
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/backend.log
    encoding: utf-8
    mode: 'a'
  
  # Rotating log file (prevents files from getting too large)
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/backend_rotating.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  # Error-only log file
  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    encoding: utf-8
    mode: 'a'

  # Database-specific log file
  database_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/database.log
    encoding: utf-8
    mode: 'a'

loggers:
  # Main backend logger
  backend:
    level: DEBUG
    handlers: [console, file, rotating_file]
    propagate: false
  
# Root logger configuration
root:
  level: INFO
  handlers: [console, error_file]

# Custom configuration section for additional control
custom:
  # Which loggers to enable (console, file, rotating_file, error_file, database_file)
  enabled_loggers: [console, file]
  
  # Packages to ignore INFO/DEBUG messages from (they'll only show WARNING and above)
  ignored_packages:
    - httpx
  
  # Custom log levels for specific packages
  package_levels:
    psycopg2: INFO

  # Log directory and file rotation settings
  log_directory: logs
  max_file_size_mb: 10
  backup_count: 5
  
  # Environment-specific settings
  development:
    console_level: DEBUG
    file_level: DEBUG
  
  production:
    console_level: INFO
    file_level: WARNING
    
  testing:
    console_level: WARNING
    file_level: DEBUG
