handlers:
  console:
    level: DEBUG
  file:
    filename: logs/backend.log

loggers:
  backend:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  database:
    level: DEBUG
    handlers: [console, file]
    propagate: false